### ISSUE TITLE
integrity checksum failed when using sha1

### ISSUE THREAD

**Issue by fanlyze** [webscopeio/react-markdown-editor#20]
npm ERR! code EINTEGRITY
npm ERR! sha1-EgURgPstt8y3KP7+Z8d+lV6SpE0= integrity checksum failed when using
sha1: wanted sha1-EgURgPstt8y3KP7+Z8d+lV6SpE0= but got sha1-OGnszQkiopHnGPQZnVjA
HfBQXHY=. (3880624 bytes)

why？

**Comment by jvorcak** [comment]
@fanlyze thanks for taking your time and creating an issue. Can you please give me more information about how this happened?

**Comment by fanlyze** [comment]
@jvorcak I just run npm install，like this：
E:\React\react-markdown-editor>npm install  --registry=https://registry.npm.taob
ao.org
npm WARN tar ENOENT: no such file or directory, open 'E:\React\react-markdown-ed
itor\node_modules\.staging\fsevents-592e435e\node_modules\mkdirp\bin\cmd.js'
npm WARN tar ENOENT: no such file or directory, open 'E:\React\react-markdown-ed
itor\node_modules\.staging\es5-ext-f2660e5d\string\#\@@iterator\implement.js'
npm WARN tar ENOENT: no such file or directory, open 'E:\React\react-markdown-ed
itor\node_modules\.staging\fsevents-592e435e\node_modules\mkdirp\bin\usage.txt'
npm WARN tar ENOENT: no such file or directory, open 'E:\React\react-markdown-ed
itor\node_modules\.staging\es5-ext-f2660e5d\string\#\@@iterator\index.js'
npm WARN tar ENOENT: no such file or directory, open 'E:\React\react-markdown-ed
itor\node_modules\.staging\es5-ext-f2660e5d\string\#\@@iterator\is-implemented.j
s'
npm WARN tar ENOENT: no such file or directory, open 'E:\React\react-markdown-ed
itor\node_modules\.staging\es5-ext-f2660e5d\string\#\@@iterator\shim.js'
npm WARN tar ENOENT: no such file or directory, open 'E:\React\react-markdown-ed
itor\node_modules\.staging\core-js-2a5f6497\fn\set\from.js'
npm WARN tar ENOENT: no such file or directory, open 'E:\React\react-markdown-ed
itor\node_modules\.staging\core-js-2a5f6497\fn\set\index.js'
npm WARN tar ENOENT: no such file or directory, open 'E:\React\react-markdown-ed
itor\node_modules\.staging\core-js-2a5f6497\fn\set\of.js'
npm WARN tar ENOENT: no such file or directory, open 'E:\React\react-markdown-ed
itor\node_modules\.staging\fsevents-592e435e\node_modules\needle\test\utils\form
idable.js'
npm WARN tar ENOENT: no such file or directory, open 'E:\React\react-markdown-ed
itor\node_modules\.staging\fsevents-592e435e\node_modules\needle\test\utils\prox
y.js'
npm WARN tar ENOENT: no such file or directory, open 'E:\React\react-markdown-ed
itor\node_modules\.staging\fsevents-592e435e\node_modules\needle\test\utils\test
.js'
npm WARN tar ENOENT: no such file or directory, lstat 'E:\React\react-markdown-e
ditor\node_modules\.staging\fsevents-592e435e\node_modules'
npm WARN tar ENOENT: no such file or directory, open 'E:\React\react-markdown-ed
itor\node_modules\.staging\es5-ext-f2660e5d\test\array\#\entries\implement.js'
npm WARN tar ENOENT: no such file or directory, open 'E:\React\react-markdown-ed
itor\node_modules\.staging\es5-ext-f2660e5d\test\array\#\entries\index.js'
npm WARN tar ENOENT: no such file or directory, open 'E:\React\react-markdown-ed
itor\node_modules\.staging\es5-ext-f2660e5d\test\array\#\entries\is-implemented.
js'
npm WARN tar ENOENT: no such file or directory, open 'E:\React\react-markdown-ed
itor\node_modules\.staging\es5-ext-f2660e5d\test\array\#\entries\shim.js'
npm WARN tar ENOENT: no such file or directory, open 'E:\React\react-markdown-ed
itor\node_modules\.staging\es5-ext-f2660e5d\test\array\#\exclusion.js'
npm WARN tar ENOENT: no such file or directory, lstat 'E:\React\react-markdown-e
ditor\node_modules\.staging\es5-ext-f2660e5d\test\array'
npm WARN tar EPERM: operation not permitted, open 'E:\React\react-markdown-edito
r\node_modules\.staging\es5-ext-f2660e5d\number\max-safe-integer\index.js'
npm WARN tar ENOENT: no such file or directory, open 'E:\React\react-markdown-ed
itor\node_modules\.staging\es5-ext-f2660e5d\number\max-safe-integer\implement.js
'
npm WARN tar ENOENT: no such file or directory, open 'E:\React\react-markdown-ed
itor\node_modules\.staging\es5-ext-f2660e5d\number\max-safe-integer\is-implement
ed.js'
npm WARN eslint-config-react-app@2.1.0 requires a peer of babel-eslint@^7.2.3 bu
t none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@2.1.0 requires a peer of eslint-plugin-jsx-a11y
@^5.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fse
vents):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'E:\React\r
eact-markdown-editor\node_modules\.staging\fsevents-592e435e'

npm ERR! code EINTEGRITY
npm ERR! sha1-EgURgPstt8y3KP7+Z8d+lV6SpE0= integrity checksum failed when using
sha1: wanted sha1-EgURgPstt8y3KP7+Z8d+lV6SpE0= but got sha1-APHWGA5wvL83RREPb3/t
5Jlx7PY=. (3524676 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zyf\AppData\Roaming\npm-cache\_logs\2018-06-01T15_39_01_12
2Z-debug.log

E:\React\react-markdown-editor>

**Comment by fanlyze** [comment]
@jvorcak sorry，i forget to see readme. I success run with "yarn install".
